spring:
  profiles:
    active: huaweiregistercenter
  application:
    name: eureka-center
tecent-registercenter-host: 192.168.1.100
tecent-registercenter-port: 1111
huawei-registercenter-host: 192.168.1.100
huawei-registercenter-port: 1111