spring:
  profiles:
    active: huaweiregistercenter
  application:
    name: eureka-center
tecent-registercenter-host: 119.45.14.75
tecent-registercenter-port: 1111
huawei-registercenter-host: 139.9.139.63
huawei-registercenter-port: 1111