

spring:
  application:
    name: hello-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10  #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    lease-expiration-duration-in-seconds: 5  #服务刷新时间配置，每隔这个时间会主动心跳一次
server:
  port: 8002
management:
  endpoints:
    web:
      exposure:
        include: "*"


