spring:
  application:
    name: config-server
    # rabbitmq相干配置
  rabbitmq:
    host: 139.9.139.63
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wangdexiao/cloudparent2config.git
          search-paths: config-repo/
          username: wadexi2207@163.com
          password: Wdx123123123.
          # 开启启动时直接从git获取配置
          clone-on-start: true
    bus:
      enabled: true
      trace:
        enabled: true

server:
  port: 7001
eureka:
  client:
    service-url:
      defaultZone: http://139.9.139.63:1111/eureka/,http://119.45.14.75:1111/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10  #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    lease-expiration-duration-in-seconds: 5  #服务刷新时间配置，每隔这个时间会主动心跳一次
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'

